const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Read package.json to get the version
const packageJson = require('../package.json');
const version = packageJson.version;

// Define the path to the ls_info.json
const infoFilePath = path.resolve(__dirname, '../src/common/tracking/ls_info.json');

// Create an object with the version
const info = { _comment: 'generated by `../../../scripts/set_ls_version.js`', version };

// Write the info object to info.json
fs.writeFileSync(infoFilePath, JSON.stringify(info, null, 2) + '\n');
console.log(`Copied the package.json version ${version} to ${infoFilePath}.`);

execSync(`git add ${infoFilePath}`, { stdio: 'inherit' });
